version: '3.8'
services:
  cli:
    build:
      context: .
    environment:
      HOMEBREW_GITHUB_API_TOKEN: $GITHUB_TOKEN
    volumes:
      - ./:/home/dev.user/homebrew-core
      - ~/.aws:/home/dev.user/.aws
