version: '3.8'
services:
  test_with_rvm:
    build:
      context: .
      dockerfile: ./with_rvm.dockerfile
    environment:
      HOMEBREW_GITHUB_API_TOKEN: $GITHUB_TOKEN
    volumes:
      - ./:/home/dev.user/homebrew-core
