version: '3.8'
services:
  test_with_rvm:
    build:
      context: .
      dockerfile: ./with_rvm.dockerfile
    environment:
      GITHUB_TOKEN: $GITHUB_TOKEN
    volumes:
      - ./:/home/dev.user/homebrew-core
  test_without_rvm:
    build:
      context: .
      dockerfile: ./without_rvm.dockerfile
    environment:
      GITHUB_TOKEN: $GITHUB_TOKEN
    volumes:
      - ./:/home/dev.user/homebrew-core
